### ISSUE TITLE
树莓派3b，出现accepted, but can't get dst ip. total conn:0

### ISSUE THREAD

**Issue by 253153** [koolproxy/koolproxy-bin#9]
树莓派3b，使用的是arm。
使用时已经出现“listen socket on [0.0.0.0]:3000 success”
但是其他电脑代理树莓派ip地址的3000端口后，
电脑访问网页时失败，
同时树莓派显示“192.168.88.103:63582 accepted, but can't get dst ip. total conn:0”
192.168.88.103是电脑的ip地址。

**Comment by silenceleaf** [comment]
我也有同样的问题

**Comment by silenceleaf** [comment]
3.7.2 版本

**Comment by binggz** [comment]
很想知道树莓派b+的lede上怎么安装这个。请大虾指教
binggz@gmail.com

**Comment by houzi-** [comment]
@253153 @silenceleaf @binggz 
树莓派请使用这个二进制来运行
https://koolproxy.com/downloads/aarch64

**Comment by 253153** [comment]
@houzi-
二进制文件好像不适用于树莓派3b，运行时直接显示 cannot execute binary file: Exec format error

执行 file ./aarch64
显示 ./aarch64: setuid, setgid, sticky ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, stripped

如果是从koolshare下载的arm文件，可以运行，但是会出现之前写的问题。
执行 file ./arm
显示 ./arm: ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), statically linked, stripped

**Comment by houzi-** [comment]
@253153 你这个树莓派用的是什么系统？

**Comment by houzi-** [comment]
如果是openwrt的话应该是可以运行的

**Comment by 253153** [comment]
@houzi- 系统是官网的Debian，没有用OpenWrt

**Comment by houzi-** [comment]
@253153 
https://downloads.openwrt.org/releases/18.06.1/targets/brcm2708/
